### ISSUE TITLE
Switch to cgroup v2

### ISSUE THREAD

**Issue by eroussy** [seapath/meta-seapath#227]
**Astract**
All SEAPATH Yocto machines use only cgroupv1. We should switch to cgroup v2 and verify that it does not harm performance.

**Work to do**
The kernel parameter `systemd.unified_cgroup_hierarchy=0` is included in `conf/machine/seapath-machine-common.in`.
It should be removed, and cyclictest+latency test should be done to ensure that it does not impact performances.

**Comment by dupremathieu** [comment]
Done in https://github.com/seapath/meta-seapath/pull/291
