### ISSUE TITLE
scarthgap: remove remaining outdated backport

### ISSUE THREAD

**Issue by emontmas** [seapath/meta-seapath#266]
There are still some recipes that have been backported for kirkstone or previous yocto versions that are now packaged in equal or higher versions in other yocto layers. Outdated backports should be removed to use latest versions and remove recipe duplicate.
Some of these recipes also have specific modifications for Seapath that should be kept in appropriate bbappend files.

Outdated backport that I have found:
* `net-snmp`: version 5.9.1 was backported more than 3 years ago when only version 5.8 was available, but now the recipe is packaged in version 5.9.4 in meta-networking
* `python3-schedutils`: version 0.6 is now available in meta-python with scarthgap. It also seams that the version in meta-seapath has additional modifications that might be upstreamed
* `python3-linux-procfs`: added to meta-python with mickledore, now in version 0.7.3 with scarthgap, while the meta-seapath backport is only in 0.7.0
* `kbd`: version 2.6.4 is available on scarthgap in poky, while meta-seapath still has version 2.5.0 because required with kirkstone

**Comment by Paullgk** [comment]
Hello @Revalioli 
This have been resolved in https://github.com/seapath/meta-seapath/pull/267
