### ISSUE TITLE
Should current SEAPATH build run on Intel NUC 7i3BNK (Kaby Lake)

### ISSUE THREAD

**Issue by salerio-gs** [seapath/meta-seapath#3]
This is more of a question (I posted it in SLACK as well but I don't know who looks at that at present). I built the **seapath-flash-efi** image and  setup a USB stick as per the documentation. The NUC boots, 4 penguins appear and an error related to a missing EFI_MEMMAP (I think) kernel configuration and no prompt.

**Comment by dupremathieu** [comment]
We tested only with server platforms, not with NUCs. It is possible that one module for this platform is missing.
It is difficult to investigate without the platform. Would it be possible to have the screen picture to help us ?

**Comment by salerio-gs** [comment]
Yes of course, I will also do a few more experiments to track the issue, I was just asking in case you knew anything obvious :) Out of interest would you expect Virtual Box to work?

**Comment by ebail** [comment]
Yes, you can use seapath-flash-efi on a VM (Virtual Box for instance).
Regarding the support of Intel NUC 7i3BNK, some logs would be definitely helpful as we do not have this Hardware to test for the moment.
Thanks

**Comment by salerio-gs** [comment]
Back at work now, so will try to find the time to provide logs ASAP.

**Comment by salerio-gs** [comment]
More information. I removed the quiet option from the flasher image WKS file and can now see the kernel boot log on the console, it seems that the kernel can't find the root file system.

The actual error is:
`Waiting for root device PARTUUID=c16f20b0-24f9-4990-98b3-82c3b57cad17
`
This is odd as when I mount the USB stick I am booting from into my Ubuntu machine the PARTUUID reported for the root partition matches that listed above! I suspect there is something missing from the kernel configuration?

I have no problems booting by NUC using either the default poky zeus kernel (MACHINE=genericx86-64) or the Intel kernel from meta-intel.

**Comment by salerio-gs** [comment]
The problem is solved by adding some important kernel config fragments required to boot on Intel NUC devices. In my fork of this repo (https://github.com/salerio-gs/meta-seapath) the branch **intel-nuc** contains the fixe in the form of a new config fragment **nuc.cfg**. I am not sure yet how contributions are to work for SEAPATH so would be grateful if you could advise if this change could be accepted or if you would prefer I keep it local for the time being.
