### ISSUE TITLE
Flasher image seems to assume French keyboard layout

### ISSUE THREAD

**Issue by salerio-gs** [seapath/meta-seapath#4]
The image **seapath-flasher-efi** image when booted (from USB stick) in Virtual Box assumes French language keyboard layout thus making it difficult to use with a UK keyboard.

**Comment by salerio-gs** [comment]
Some research leads to the conclusion that systemd picks the alphabetically first keymap (which just happens to be azerty), I was able to workaround the issue by running ` loadkeys -d`.  I'm not sure exactly what is supposed to happen when systemd starts however.

**Comment by salerio-gs** [comment]
Same appears to happen for **seapath-dbg-image-votp** , can be worked around by using `loadkeys -d` or` localctl set-keymap uk`.

**Comment by ebail** [comment]
Hi @salerio-gs,

Thanks for your feedback. The default language should not be FR but US.
The use of loadkeys / localctl is correct to change that.

I let this issue opened until the commit is done.

**Comment by salerio-gs** [comment]
Great

**Comment by salerio-gs** [comment]
I will send a PR to fix this ?

**Comment by ebail** [comment]
Thanks for your answer. I did it in https://github.com/seapath/meta-seapath/pull/9
